
class Locators:

    url ='https://s8.asyx.com'
    username = 'asyxdummy'
    password ='Asyx!4362023'

    # By.CSS_SELECTOR, '[name="quoteEnabled"]+span.switch-slider'
    # By.CLASS_NAME, 'nav-link.nav-dropdown-toggle'
    # By.CSS_SELECTOR, 'a[href*="programmanagement"]'
    # By.CSS_SELECTOR, 'button.btn-primary i.fa-plus'
    # By.CSS_SELECTOR, 'input[name="enable"] + span.switch-slider'
    # By.CSS_SELECTOR, 'input[name="buyerMultiple"] + span.switch-slider'
    # By.CSS_SELECTOR, 'input[name="enable"][aria-checked="false"]+span.switch-slider'
    # By.CSS_SELECTOR, 'form>:nth-child(4)>div>div>:nth-child(2)>.mx-1>.switch-input+span'
    # By.CSS_SELECTOR, '[name="quoteEnabled"]+span.switch-slider'
    # By.ID, 'react-select-6-input'
    # By.CSS_SELECTOR, 'ul.list-group>li.align-items-center:nth-child(2)'
    # By.CSS_SELECTOR, '[name="orderEnabled"]+span.switch-slider'
    # By.ID, 'react-select-6-input'
    # By.CSS_SELECTOR, '[name="partlyDespatchAdvice"]+span.switch-slider'
    # By.CSS_SELECTOR, '[name="activated"]+span.switch-slider'
    # By.CSS_SELECTOR, 'li.align-items-center:nth-child(4)'
    # By.ID, 'react-select-6-input'
    # By.CSS_SELECTOR, 'li.align-items-center:nth-child(5)'
    # By.CSS_SELECTOR, 'li.align-items-center:nth-child(6)'
    # By.CSS_SELECTOR, 'td input.form-control[type="text"][name="name"]'
    # By.CSS_SELECTOR, 'li.align-items-center:nth-child(6)'
    # By.CSS_SELECTOR, 'td>button.btn>i.fa'
    # By.CSS_SELECTOR, 'td>[name="name"]'
    # By.ID, 'btn-save-program'